### ISSUE TITLE
Does this tool support conversion nested Avro Records to ES mapping?

### ISSUE THREAD

**Issue by kant111** [happyprg/AvroSchemaRegistryConvertToESMapping#1]
Does this tool support conversion nested Avro Records to ES mapping? I don't see any recursive calls.

**Comment by SavtechSolutions** [comment]
It doesn't

**Comment by happyprg** [comment]
Would you please give me some examples what you want? so I can make some changes

**Comment by happyprg** [comment]
Please let me know if you want it
